### PR TITLE
Add experimental gba libretrocore gpsp

### PR DESCRIPTION
**Pull request by gizmo98**
Builds and runs.

### CODE REVIEW

**Comment by frthery** [comment]
Hi, just for information since 1 Feb gpsp core has poor performances (PI1):
https://github.com/libretro/gpsp/commit/fb984fcaeffe8fd99c801738d4b238f1e99e131c

because dynarec has been disabled :/

**Comment by joolswills** [comment]
Was it working for you before ? if so please report it to https://github.com/libretro/gpsp/issues/11

**Comment by gizmo98** [comment]
Did you test with dynarec enabled? Could tune the makefile if it is running with dynarec enabled.

**Comment by frthery** [comment]
Before this modification core was running good, that why i am using a version compiled before.

**Pull request merged**
