### PR TITLE
Add experimental vectrex libretrocore

### PR DESCRIPTION
**Pull request by gizmo98**
Compiles and runs.

### CODE REVIEW

**Comment by gizmo98** [comment]
Should be better now.

**Comment by joolswills** [comment]
almost - but I would either just include the .bin files in the md_ret_files (they would then install without the bios subfolder on dest), or copy manually, they dont need to be installed as they are the header files used to create the .bin files.

**Comment by joolswills** [comment]
(so only the .bin files should be copied to the install folder during source install)

**Comment by gizmo98** [comment]
Should be. But i have only tested with all files and my pi is not working atm.

**Comment by joolswills** [comment]
looks good, but ill tweak it after merge to remove the installing of the .h to the /opt/retropie-setup also (to keep it clean from source).

**Pull request merged**
