### PR TITLE
Add pcsx-rearmed as a standalone emulator

### PR DESCRIPTION
**Pull request by gizmo98**
A faster psx emulator for rpi1 users.

### CODE REVIEW

**Comment by joolswills** [comment]
Please can you merge the fixes in another branch and resubmit (alternatively I can manually merge this all as one when I have time).

**Comment by gizmo98** [comment]
Yes. I will do it later.

**Comment by joolswills** [comment]
manually merged as a single commit.

**Comment by joolswills** [comment]
There were a bunch of tabs in the file again. Please can you check before submitting pull requests that the indentation is correct. thanks.

**Pull request closed without merging**
