### PR TITLE
added options to launch menu to switch render resolution of retroarch #531

### PR DESCRIPTION
**Pull request by joolswills**
@gizmo98

The final piece ? As discussed on ticket #531 this now includes the ability to switch retroarch render resolution.

Options are

"320x240"
"640x480"
"960x720"
"1280x960"
"Use video output resolution"
"Use config file resolution"

it defaults to 640x480 - I thought about having a different default for pi2, but then I thought maybe best to err on the side of caution and go with best performance at a res that should be enough as a default. And of course it is easily switchable. But let me know what you think and if there is enough choice.

### CODE REVIEW

**Comment by joolswills** [comment]
I forgot about overlays of course, which could look better at 960x720. let me know if 640x480 is ok as a default anyway or if you definitely think pi2 would be better at higher default and I can put some additional logic in.

**Comment by gizmo98** [comment]
Should be ok. I will check it tomorrow.

**Comment by gizmo98** [comment]
Please update the retroarch binary. If i do a binary update aspect ratio will not be respected if 640x480 is set. All libretrocores are stretched.

**Comment by joolswills** [comment]
I didn't notice that - but maybe because I was testing on a 4:3 screen.

Binaries are updated (quite a size difference now due to all the overlays / assets etc)

**Pull request merged**
