### PR TITLE
mupen64plus-libretro: Don't use rpi2 target for now.

### PR DESCRIPTION
**Pull request by gizmo98**
It always crashes with a segfault. If -mfpu=neon-vfp4 is set the libretrocore will crash.

### CODE REVIEW

**Comment by joolswills** [comment]
I'd prefer the lines removed rather than commented out (and possibly a comment put in). I know I'm fussy - sorry :)

**Comment by gizmo98** [comment]
Yup. Just wait. I will test something else.

**Comment by joolswills** [comment]
we want to be able to control the platform flags ourselves really from the script - but that depends on the makefile being made to allow this - so many don't (I just did fixed this with the new uae4all for example).

**Comment by joolswills** [comment]
Should this be merged or you need to do some more testing still ? thanks for all the changesets.

**Comment by gizmo98** [comment]
It is working now with on a fixed fork. I will close it.

**Pull request closed without merging**
