### PR TITLE
Feature/asplashscreen now actually handles individual images videos in splashscreen list sequentially in background during startup

### PR DESCRIPTION
**Pull request by free5ty1e**
-New logic in asplashscreen startup script that can actually handle each individual line in splashscreen.list separately, and display in order each image or video during startup. Emulation station will interrupt the playback sequence and take over when startup is complete, if the splash screen list takes too long.

I figured this out for my personal RetroPie load, and figured I'd share it with the project if it is deemed useful.  Feel free to reject :D

### CODE REVIEW

**Comment by joolswills** [comment]
As we currently choose a single image for display, if supporting multiple images then we would want that in the helper too. 

also please do the pull request from a new branch from our master, so we don't get the merge commits.

**Comment by free5ty1e** [comment]
OK I'll recreate the pull request to remove the merge commits.  Still learning how github fork syncing should happen.

**Comment by joolswills** [comment]
https://help.github.com/articles/syncing-a-fork/

**Comment by free5ty1e** [comment]
Yep thats what I originally followed... i guess i have to refork and start fresh, i cant get rid of these merge commits.

**Comment by joolswills** [comment]
keep your master synced with ours, have your own branch for your stuff. branch off master to feature branches to feed back to us

**Pull request closed without merging**
