### PR TITLE
Add videopac libretrocore O2EM

### PR DESCRIPTION
**Pull request by gizmo98**
Compiles and runs if o2rom.bin BIOS file is present.

### CODE REVIEW

**Comment by joolswills** [comment]
actually. ill merge it and then fix it up, as I see there are some other mkRomDirs to fix also.

**Comment by joolswills** [comment]
thanks

**Comment by gizmo98** [comment]
Yeah. Many modules use the old style mkdir:
armsnes, catsfc, cavestory, doom, fbalibretro, tyrquake, hatari, apple2

**Comment by joolswills** [comment]
They should all be sorted now.

**Pull request merged**
