### PR TITLE
Update packagecleanup.sh

### PR DESCRIPTION
**Pull request by ProxyCell**
pulseaudio & cups are not in the latest raspbian image
could more things be added for removal?

### CODE REVIEW

**Comment by joolswills** [comment]
I believe those are removed by another retropie module - as pulseaudio directly interferes (or has been said to).however, it could be argued that it was all moved to this module depending on if pulseaudio is still an issue for basic functionality.

**Comment by joolswills** [comment]
ignore my previous comment - I misread the patch. are you saying that raspbian doesn’t come with cups and pulseausio installed by default ?

**Comment by ProxyCell** [comment]
yeah, i tried removing them manually as they are written in that script file
only the wolfram and sonic-pi were possible for removal. the others were not present in the latest raspbian image (from feb 2015)

**Comment by joolswills** [comment]
it's possible someone might install them later however, and so it's still useful perhaps to have the option to remove them, but this "module" isn't too useful at present - should probably have a menu and some options.

**Comment by ProxyCell** [comment]
thanks for that @joolswills

**Pull request closed without merging**
