### PR TITLE
Snes9x and genesis plus gx

### PR DESCRIPTION
**Pull request by gizmo98**
Add snes9x-next and use genesis-plus-gx for megadrive/genesis emulation.

### CODE REVIEW

**Comment by joolswills** [comment]
please can we use the older naming for now? maybe just call it genesisplusgx for module name (and filename) - until we have all agreed on what we will do about the naming.

**Comment by gizmo98** [comment]
snes9x-next as well?

**Comment by joolswills** [comment]
yes please (can just call it snes9xnext.sh / snex9xnext for module name for now)

**Comment by joolswills** [comment]
(without my typos ;-) )

**Comment by joolswills** [comment]
Cheers.

**Pull request merged**
