### PR TITLE
Update kodi.sh

### PR DESCRIPTION
**Pull request by HerbFargus**
This fixes the black screen on exit to emulationstation

see post here: 
http://blog.petrockblock.com/forums/topic/exiting-kodi-to-emulationstation/

### CODE REVIEW

**Comment by joolswills** [comment]
Does kodi not exit cleanly then - the script has a busy loop watching the log, then tries to kill kodi - if kodi exits ok, we can leave that out and just reset the framebuffer. I'm not keen on adding this in the current form as it seems a rather heavy handed workaround.

**Comment by HerbFargus** [comment]
@joolswills It doesn't exit cleanly for quite a few people I've seen as I've trolled the forums in the past few months (including myself) it would just freeze up on the black screen when you exit to emulationstation. 

You were correct about only needing the framebuffer- I took all the log rubbish out and just left the framebuffer reset and it works just fine.

**Comment by joolswills** [comment]
Yeh so it's exiting ok, but leaves the framebuffer in an unusable state. Probably running it via runcommand may fix it too (as that does a framebuffer reset).

Please could you submit an additional pull request with just the change as a single commit - alternatively i could apply the change manually (avoids having two commits adding them removing code).

**Comment by HerbFargus** [comment]
Ok, sorry for my inexperience with github, I'm still figuring it out. I've added another pull request with runcommand and it seems to work with initial testing.

**Comment by joolswills** [comment]
np.  thanks for the contributions :)

Nothing wrong with multiple commits sometimes, but it's just tidier to have a single commit for a small change.

**Pull request closed without merging**
