### PR TITLE
Add repo for missing system themes

### PR DESCRIPTION
**Pull request by gizmo98**
Added missing themes for retropie and videopac. Can be removed if someone adds these systems to simple_latest.zip.

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks - sounds good.

I wrote to @petrockblog regarding a theme for retropie - has this been implemented upstream or it's something custom ?

It might be better to handle it all from a git repository and so changes can be pulled in upstream - your's would be fine imho until we move perhaps to the central org etc - but I'll leave this one for @petrockblog to merge. Can you give more details on the retropie theme ?

probably don't need to chown anything as the themes live in /etc/ which is ok to be owned by root imho. but a minor thing ;-) I don't think we chown the current theme - not sure.

**Comment by gizmo98** [comment]
It's something custom. It's oldschoolretropie asplashscreen with a retropie logo (bauhaus font). The videopac logo uses the original videopac font. Don't know if you are working on a new image but our new retropie menu should have at least a theme :-)

Feel free to remove chown.

**Comment by gizmo98** [comment]
I.e. to customize logo and background replace retropie.png and retropie_art_blur.png. Theme.xml is already set up. Feel free to replace these to files with official logos and backgrounds.

**Comment by petrockblog** [comment]
Thanks a lot for your additions!
In fact, I have contacted Nils from EmulationStation and asked if he would have an idea for a RetroPie theme. I am still waiting for a reply, though.
In either way, it would be great if your work would be added to the "simple theme" or another theme - hopefully there will be additional themes soon.

**Comment by gizmo98** [comment]
I removed chown. In my opinion you can merge it if simple theme will not be updated in the next time.

**Comment by joolswills** [comment]
I believe Nils is working on something for us - so I guess we should wait a bit more - if you don't mind. Unless you think we can merge this now, and then replace later ?

**Comment by joolswills** [comment]
(Not that your theme isn't appreciated though :) )

**Comment by petrockblog** [comment]
I was told by Nils that he wants to wait until we have a logo (I plan a logo contest, but some things still have to be waited for). I suggest that we use this theme for the RetroPie configuration. When we have an official logo, we can still adapt the theme accordingly.
Again, thanks a lot for your work!

**Comment by joolswills** [comment]
Competition sounds like a nice idea!
merged :) thanks @gizmo98

**Comment by gizmo98** [comment]
Yeah. Competition sounds good.

**Pull request merged**
